# Configuration for running GitHub actions
#  initially based on TYPO3 documentation: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/ExtensionTesting.html
#  and changes in https://github.com/sypets/brofix
#  but has been modified

# todo: add multiple PHP versions
# todo: add multiple TYPO3 versions
# todo: add runTests.sh
# todo: run functional tests
# todo: add PHP lint

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '42 5 * * *'

jobs:
  tests_single_php:
    name: "simple tests"
    runs-on: ubuntu-20.04
    strategy:
      # This prevents cancellation of matrix job runs, if one/two already failed and let the
      # rest matrix jobs be be executed anyway.
      fail-fast: false
      matrix:
        php: [ '8.1' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "composer validate"
        run: composer validate

      - name: "composer install"
        run: composer install

      - name: "cgl"
        run: composer cs:check

  tests_multiple_php:
    name: "simple tests"
    runs-on: ubuntu-20.04
    strategy:
      # This prevents cancellation of matrix job runs, if one/two already failed and let the
      # rest matrix jobs be be executed anyway.
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "composer validate"
        run: composer validate

      - name: "Set platform requirement 7.4"
        if: ${{ always() && matrix.php == '7.4' }}
        run: composer config platform.php 7.4.

      - name: "composer install"
        run: composer install

      - name: "cgl"
        if: ${{ always() && matrix.php == '8.1' }}
        run: composer cs:check

      - name: "phpstan"
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan -e "--error-format=github"

      - name: "Unit tests"
        run: composer test:php:unit
